### PR TITLE
HAS-372: vpublicapi: Add new response type for Stream API.

### PR DESCRIPTION
**Pull request by jayden-tan-verkada**
### Purpose
Add a new response type for Stream API endpoint.

### Test Plan
- [x] Tested with Stream API in staging.

### CODE REVIEW

**Review by haonan-vk — COMMENTED** [review]
Does it automatically generate API as well given this change?

**Comment by jayden-tan-verkada** [comment]
> Does it automatically generate API as well given this change?

Is it supposed to generate API doc based on this change? `vpublicapi-open-api-spec.yaml` and `camera.json` don't have the docs generated for the endpoints, how do I auto generate them?

**Review by haonan-vk — APPROVED** [review]
https://www.notion.so/vkda/PublicAPI-v2-c3a7a27ede3e4622bddc56cbbf6b22d7#39456a9ed0ff46f0bb8b14378b1fb06c

Approve for now. Ideally this library is used to auto generated code without manual editing any yaml/json file in the repo.

**Comment by haonan-vk** [comment]
> > Does it automatically generate API as well given this change?
> 
> Is it supposed to generate API doc based on this change? `vpublicapi-open-api-spec.yaml` and `camera.json` don't have the docs generated for the endpoints, how do I auto generate them?

Yeah, they are legacy files that don't have functions any more...

**Comment by jayden-tan-verkada** [comment]
> https://www.notion.so/vkda/PublicAPI-v2-c3a7a27ede3e4622bddc56cbbf6b22d7#39456a9ed0ff46f0bb8b14378b1fb06c
> 
> Approve for now. Ideally this library is used to auto generated code without manual editing any yaml/json file in the repo.

Just confirmed that the api doc is not auto generated. Likely need to resort to manual editing.

**Pull request merged**
